name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17.x ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build godoc2md
      run: "cd cmd/godoc2md; go build"

     -name: Build godocserve
      run: "cd cmd/godocserve; go build"

    - name: Test
      run: go test -v ./...
